name: CI-CD

on: push

jobs:
  continuous-integration:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Using Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.
      - name: Install dependencies and execute tests
        run: |
          npm install
          npm run test
  continuous-delivery:
    name: Deployment to Lambda Function
    needs: continuous-integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Zip files
        run: |
          zip -r lambda.zip .
      - name: Send to Lambda
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: expressJsApi
          zip_file: lambda.zip
